### ISSUE TITLE
Roll vibrating near center

### ISSUE THREAD

**Issue by DeadlyMercury** [fred41/G940-firmware-fixes#1]
Hello, just tried your patch and it is really cool, but found one little bug caused due to centering forces I guess.

If I release hand from stick - I can see it vibrating near center, I guess because motor fails to hold strict center position and misses it every time on roll axis. Therefore there is no such vibration on pitch axis and I can move stick little bit around its center without vibration and force.

So I guess pitch and roll axis has different settings and roll axis settings has very small force dead zone near center causing stick to vibrate near it.

**Comment by DeadlyMercury** [comment]
Oh, I see it is a known bug: 
https://forums.eagle.ru/showpost.php?p=3907148&postcount=17

**Comment by fred41** [comment]
I am assuming you are using the latest version of my patch.

My 'center play' related modification is based on an increased 'minimal voltage' for the dc motors.
The minimal voltage is essential to get an acceptable 'center play' window, because any dc motor doesn't start to output a torque, before all the inner friction forces are compensated.
Hence, an optimal voltage, will result in the smallest possible "center play" window.

Now the problem is: **Each device is different**, because of aging, modifications, etc.
Unfortunatelly, there is now easy way for me, to export this parameter (minimal voltage) to the user.
So i finally implemented a value that is basically a compromise. For me this value works perfect, because i did some simple, but very usefull modifications.
1. fixed the two (roll) ball bearings on their axis (this axis is produced with a diameter to small)
2. moved the motors closer to the clog-segments to eleminate the play within the clogs
3. replaced the grease for all slide bearings with a higher viscosity grease

I would recomment to adapt your device accordingly, because you will get an very precise device this way and the oscillations will stop.
